### ISSUE TITLE
unable to find an inherited method for function ‘lhs<-’ for signature ‘"NULL"’

### ISSUE THREAD

**Issue by ParkerWilliam** [bcallaway11/did#1]
I’m trying to use your r package to do a did analysis with multiple groups and time of treatment. I use the mp.spatt function and using example provided In your R documentation: 

data(mpdta)
out <- mp.spatt(lemp ~ treat, xformla=~lpop, data=mpdta,
                panel=TRUE, first.treat.name="first.treat",
                idname="countyreal", tname="year",
                bstrap=FALSE, se=TRUE, cband=FALSE)

summary(out)

summary(out$aggte)

This example runs smoothly. However when removing the xformla=~lpop argument that is described as “A optional one sided formula” it seems to return the following error: 

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘lhs<-’ for signature ‘"NULL"’

if have tried to debug the code. 

The error occurs in line 28 and 29 in the compute.mp.spatt function: 

debug: pformla <- xformla

debug: formula.tools::lhs(pformla) <- as.name("G")

pformla is assigned a NULL and then lhs is using this NULL and the error occurs. 

Am I doing something wrong here or can you recreate the error?

**Comment by bcallaway11** [comment]
Hi Parker,

You are right that it is a bug.  Thanks for sending it to me.  The fix
should be available on github now, and I am updating the package on CRAN
now.

Thanks,
Brant

**Comment by ParkerWilliam** [comment]
Hi Brant

thanks for the fix i'm going to try right away - and thanks for a cool package. It really seems like the only one that does the job with did with multiple groups and treatments - good stuff. 

i'm just gonna try it then close the issue. 

kind regards 

William
