### ISSUE TITLE
Average Effect by Time Period after Treatment

### ISSUE THREAD

**Issue by jkortner** [bcallaway11/did#107]
Thanks for the great package!

I'm using the `did` package to analyse an intervention with staggered adoption in different regions. I have monthly data with more than 24 post-treatment months.

I expect a delay of the treatment effect, and I'm interested in the long term effect. Thus, I would like to compute the average effect of the treatment aggregated, e.g., for the first 6 months, 7-12 months, 13-18, and 19-24 after treatment. Would this be possible with one of the functions?

(The calendar option is not relative to the treatment time as I understand it.)

**Comment by bcallaway11** [comment]
Hi John,

This is not something that we have "off-the-shelf" though it should be possible with a medium amount of work.  Basically, you could run our event study, average the event study estimates together in whatever bins you want (e.g., 7-12 months) to get a point estimate.  For inference, our event study also returns the influence function as a matrix; you could get the corresponding columns of the influence function, average them together (across included event times), and then compute an estimate of the asymptotic variance as `mean(inffunc^2)` where `inffunc` is the averaged together influence function.

Here is some example code along these lines.  Basically, I am using the data from our package and then computing the average effect between "on impact" effect and after one period of exposure to the treatment (but I think you should be able to easily modify this towards whatever "bins" you would like to use).

``` r
library(did)
library(BMisc)
data(mpdta)

out <- att_gt(yname = "lemp",
              gname = "first.treat",
              idname = "countyreal",
              tname = "year",
              xformla = ~lpop,
              data = mpdta,
              control_group="notyettreated"
)

dyn <- aggte(out, type="dynamic")

# compute average across first two periods of exposure

# which lengths of exposure to keep
e_keep <- dyn$egt %in% c(0,1)

# actually compute the average
avg_att_e <- mean(dyn$att.egt[e_keep])

# get the influence function
keep_if <- dyn$inf.function$dynamic.inf.func.e[,e_keep]
n <- nrow(keep_if)
# average influence function
avg_if <- apply(keep_if, 1, mean)
# estimate asymptotic variance
V <- mean(avg_if^2)
# get standard errors
se <- sqrt(V)/sqrt(n)

# results
data.frame(avg_att_e=avg_att_e, se=se)
#>     avg_att_e         se
#> 1 -0.03743738 0.01109951
```

I hope this code will get you a good start on what you are looking for, but keep me posted if you run into other issues.

Brant

**Comment by bcallaway11** [comment]
Good answer, Pedro.  I'm going to close this one.
