### ISSUE TITLE
Package ‘did’ was removed from the CRAN repository.

### ISSUE THREAD

**Issue by tmsgaillard** [bcallaway11/did#137]
Hi team,
First I would like to thank you profoundly as I've been using your package for a couple of months and found it very easy to use from the beginning as it's super well documented.

Today, as I wanted to import it from CRAN, I found out it was "removed" as you can read on the [CRAN page](https://cran.r-project.org/package=did). I could still download the archive and install the package this way, but wanted to have your thoughts and know if you had a plan to re-upload `did` on CRAN. I'm not very familiar as to how CRAN uploads and integrations works.

Thank you!

**Comment by bcallaway11** [comment]
Hi Thomas,

It should be back very soon.  This was downstream of some issues with other packages that have been fixed now, and I think it is just propagating back through now.  

Brant

**Comment by bcallaway11** [comment]
It is back now!

https://cran.r-project.org/package=did
