### ISSUE TITLE
Big differences between using universal or varying base period

### ISSUE THREAD

**Issue by simon-lowe** [bcallaway11/did#142]
Hi,

First of all, thank you for a great package! I was wondering whether you could help me figure out how there could be a big difference between the exact same specification and data using the universal or the varying base period. I have a situation where I get the following:
![image](https://user-images.githubusercontent.com/57216897/182453947-6e6fece2-26b0-4e17-914d-de2ea8b73060.png)

In blue is post-treatment, in red pre-treatment with varying base period and in green pre-treatment with universal base period.

I apologize for the crude paint representation of the corresponding graphs, but these are from confidential admin data on a secure server. I also apologize for the lack of a code or reproducible example but since I haven't figured out how this is happening, I haven't been able to create a code which reproduces this.

Thank you for your help,
Simon

**Comment by bcallaway11** [comment]
Hi Simon,

You may have already seen this, but please check out this post about differences between "universal" and "varying" base periods: https://bcallaway11.github.io/posts/event-study-universal-v-varying-base-period

Your picture actually looks quite similar to the figure there involving "anticpation" effects.  At any rate, that's my first thought about what's going on here.  

Please feel free to follow up!

Brant

**Comment by simon-lowe** [comment]
Hi Brant,

Thanks a lot for your super fast answer! I hadn't seen this, I stupidly only looked at the posts on the package website and on Pedro's website. Sorry about that!

It might be related to this, I'm going to think about it and try some things out. 

I had thought about it being related to anticipation, but in my head this should've meant simply a translation of every point, but I think I understand why that is wrong.

Thank you again for your help and the great package!
Simon

**Comment by simon-lowe** [comment]
Hi Brant,

Sorry to re-open this old thread. I thought I had understood this issue but today I was looking at something new and I got the following when comparing universal vs varying:
![image](https://user-images.githubusercontent.com/57216897/222208330-f8860ecb-15bf-4ebb-9d61-aa1b308b8a90.png)

And that I am struggling to understand how make sense of it with simply the shift. This is a case where I'm using the not-yet treated. Any thoughts?

Thanks again for your help and for the great package!
Simon
