### ISSUE TITLE
Time windows in staggered DiD

### ISSUE THREAD

**Issue by cjing1** [bcallaway11/did#149]
Thank you again for the amazing method and package. 

I have another question regarding the length of time windows in staggered DiD. In regular DiD, we usually select equal lengths of pre and post-treatment periods as time windows (ex. 30 days before and after trt). However, in staggered DiD, since the trt units are treated at different times, the ATT is aggregated based on the weight of the length of exposure time, my questions are: 

1. In staggered adoption cases, should we still select equal lengths of pre and post-treatment periods? 
2. Is it make sense to do robustness checks with different post-treatment lengths (ex. with the same 30 days before, check 30/40/50/60 days post treatments periods)? Or should I follow equal lengths and do 30/40/50/60 days before and after trt instead? 

Thank you in advance for any suggestions and comments.

**Comment by bcallaway11** [comment]
It should be fine to have different “windows” on each side of the treatment.  I don’t think there is any issue that will arise from having different numbers of periods.  Hope that helps.

Brant

**Comment by cjing1** [comment]
I want to share some interesting findings. 

When I set a fixed pre-trt time window (ex. 30 days) and test different post-trt windows (ex. 30,60,90,120, etc.) The result is robust and consistent across different aggregate methods (simple, group, dynamic). 

But if I use the same length of pre-trt time and post-trt time window (ex. 120 before and after). The result is inconsistent across different aggregate methods when the time window is large (120 and above). Only the simple and dynamic methods' results are significant, but the group aggregate is no longer significant. And it happens across different DVs in my study. 

May I ask for some insights? Is it because the large same lengths of pre windows include more noise in the calculation that leads to the insignificant? But why group aggregate is the only one sensitive to the change? 

Thank you.
