### ISSUE TITLE
Error in family$linkfun(mustart)

### ISSUE THREAD

**Issue by PhantomKidding** [bcallaway11/did#153]
I'm running into the error below when calling the att_gt() function.

Error in family$linkfun(mustart) : 
  Argument mu must be a nonempty numeric vector

I walked through your source code (version 2.1.2) and found the problem is caused by line 76 at compute.att_gt() function.
`disdat <- data[data[, tname] == tlist[t + tfac] | data[, tname] == tlist[pret], ]`
If `disdat` is empty, then the `glm` at line 101 will throw the error.

Any quick fix for it?

Thanks in advance.

**Comment by bcallaway11** [comment]
Hi, thanks for the message.  Do you have an example that you could send me where this issue comes up?

Thanks,
Brant

**Comment by PhantomKidding** [comment]
Thanks for responding promptly. I attached the anonymized data and used the following code.
[data.csv](https://github.com/bcallaway11/did/files/9978608/data.csv)

```
data = read.csv('data.csv')
m <- att_gt(yname = "y",
             tname = "time",
             idname = "id",
             gname = "first",
             xformla = ~a+b+c+d+e+f+g,
             data = data,
             control_group = "notyettreated",
             panel=T
             , pl=T, cores=8
             , alp=0.05
)
```

**Comment by bcallaway11** [comment]
Hello, I quickly looked through this, and I think the issues are mainly related to small group sizes and lack of variation in the covariates.  Also, given that the data is an unbalanced panel, I'd recommend adding the argument `allow_unbalanced_panel=TRUE`. For example, the following code runs for me

```
m <- att_gt(yname = "y",
            tname = "time",
            idname = "id",
            gname = "first",
            xformla = ~1, #~a+b+c+d+e+f+g,
            data = data,
            control_group = "notyettreated",
            panel=T, allow_unbalanced_panel = T
            , pl=T, cores=1
            , alp=0.05
)

aggte(m, type="dynamic", na.rm=TRUE)
```
though I notice that if I include any covariates, I get errors about no variation in the covariates within groups, this would mean that it is infeasible to include those covariates.

Hope this helps,
Brant
