### ISSUE TITLE
Singular matrix and coefficient

### ISSUE THREAD

**Issue by liqizheng0328** [bcallaway11/did#163]
Dear Sir or Madam,

There are two questions I could not find the way to solve it. I would appreciate some feedback on these problems.
(1) As is shown in the code and error below, how could I check this problem and solve it. (I  have dropped the NA and repeated observation, and it works in stata by reghdfe)
`> out1 <- att_gt(yname="Y",
+                tname="year",
+                idname="idnumber1",
+                gname="enteryear",
+                xformla=~labor_productivity+lnassets+lnage,
+                data=did,
+                panel = FALSE)
Error in solve.default(crossprod(wols.x.pre.treat, int.cov)/n) : 
  Lapack routine dgesv: system is exactly singular: U[4,4] = 0
In addition: There were 11 warnings (use warnings() to see them)
> out1 <- att_gt(yname="Y",
+                tname="year",
+                idname="idnumber1",
+                gname="enteryear",
+                xformla=~labor_productivity+lnassets+operating,
+                data=did,
+                panel = FALSE)
Error in solve.default(crossprod(wols.x.pre.treat, int.cov)/n) : 
  system is computationally singular: reciprocal condition number = 3.27372e-19
In addition: There were 11 warnings (use warnings() to see them)`

(2) How can I output the coefficient of the control variable in this package, as it seems not to provide the argument.

Thank you very much!

**Comment by bcallaway11** [comment]
The error message is saying that the design matrix isn't invertible at least for some combinations of groups and time periods.  Will the code run if you use fewer covariates?

**Comment by liqizheng0328** [comment]
Thanks for your reply
Yes, it works when using fewer covariates.

> The error message is saying that the design matrix isn't invertible at least for some combinations of groups and time periods. Will the code run if you use fewer covariates?
