### ISSUE TITLE
honest_did function

### ISSUE THREAD

**Issue by nazaninsk** [bcallaway11/did#165]
Dear Dr. Callaway,

It seems that the honest_did function is not accessible in the current version of the R package, although I was able to generate the results previously. I would appreciate it if you could help me with this. Thank you very much for your continued support regarding our questions.

Best regards,
Nazanin

**Comment by pedrohcgs** [comment]
Hi Nazanin,
We have decided to keep things separate.

You can access the functions that integrate the packages in this Github repo: https://github.com/pedrohcgs/CS_RR 

Thanks
