### ISSUE TITLE
how could I use TWFE when using att_gt

### ISSUE THREAD

**Issue by liqizheng0328** [bcallaway11/did#166]
Dear Professor,

I am writing to inquire about the "att_gt" function in R. Specifically, I would like to know how to implement the Two-Way Fixed Effects (TWFE) model in this function, in order to control the unit and time fixed effects. It appears that "att_gt" does not provide options for fixed effects, unlike the "reghdfe" function in Stata. Would it be appropriate to use LSDV instead?

Thank you for your time and consideration.

Best regards,
Li Qizheng

**Comment by pedrohcgs** [comment]
Hi Li,
The point of our paper and our package is to avoid using TWFE linear models
in setups with treatment effect heterogeneity.
I would encourage you to check the paper (ungated version):
https://pedrohcgs.github.io/files/Callaway_SantAnna_2020.pdf

Thanks
===============================
*Pedro H. C. Sant'Anna*
Department of Economics
Vanderbilt University
615-875-8448 (phone)
***@***.***
<https://email.vanderbilt.edu/owa/redir.aspx?SURL=R33SAibMcqASxYI7tVlx3_2Xx09NkN6m1ZKVuyK8lL42lUjfQp_SCG0AYQBpAGwAdABvADoAcABlAGQAcgBvAC4AaAAuAHMAYQBuAHQAYQBuAG4AYQBAAHYAYQBuAGQAZQByAGIAaQBsAHQALgBlAGQAdQA.&URL=mailto%3apedro.h.santanna%40vanderbilt.edu>
https://pedrohcgs.github.io
===============================
