### ISSUE TITLE
Covariate-Specific Treatment Effects

### ISSUE THREAD

**Issue by dvignon** [bcallaway11/did#177]
When conditioning on covariates for the estimation, is there any way to retrieve the time-group treatment effects conditioning on the covariates? Or is the only way to do this to run the estimation unconditionally for different populations? The covariates here are discrete. 
Thank you for your help and time.

**Comment by bcallaway11** [comment]
Yes, currently this best way to do this is to just use subpopulations defined by the discrete covariate and construct estimates separately.  It's on our radar to add support for doing this automatically.
