### ISSUE TITLE
Can I use DiD package for data that only  has two-period two-group?

### ISSUE THREAD

**Issue by 49470952** [bcallaway11/did#199]
In my data, there is one intervention group and one control group. Members in the intervention group started their intervention at the same time while members in control group have never been treated. I am wondering if it is still legit to use DiD package for simple two-group two-period data structure? Also, is the overall ATT equivalent to DiD value?

Thank you!

**Comment by bcallaway11** [comment]
Yes, this will work, there should be no issues.

**Comment by 49470952** [comment]
Thank you for confirming! I have one follow-up question about the overall ATT: is the estimated ATT equivalent to the DID value from using the formula (𝐴_𝑝𝑟𝑒−𝐴_𝑝𝑜𝑠𝑡 )−(𝐵_𝑝𝑟𝑒−𝐵_𝑝𝑜𝑠𝑡) in a two-group two period data setting? I am asking because I found there is a discrepancy between these two values. Hope you can help me for the interpretation of the ATTs.

Thank you very much in advance!

**Comment by pedrohcgs** [comment]
With two time periods only, no covariates, they should be numerically the
same.

----------------------------------------------------
*Pedro H. C. Sant'Anna*
*https://psantanna.com <https://psantanna.com>*

----------------------------------------------------
Warning: This email may contain confidential or privileged information
intended only for the use of the individual or entity to whom it is
addressed. If you are not the intended recipient, please understand
that any disclosure, copying, distribution, or use of the contents
of this email is strictly prohibited.
----------------------------------------------------

**Comment by 49470952** [comment]
Thanks very much for the prompt reply. I attached the data setup (first few obs) and the R code used for ATT estimation on a two period two group dataset.

In this dataset, intervention obs and target obs with same matchto No. are pre-matched (matchto is the only covariate adjusted in the model). month=1 represents pre-period and month=2 represents postperiod. First.treated indicates the month of treatment. eci is the id variable and value is the outcome variable. 

By running the r code below, I received an error message "No pre-treatment periods to test". The overall ATT estimate was -284, numerically very different from the DiD value (41) calculated using the formula (intervention_post−intervention_𝑝re )−(Target_𝑝ost−Target_𝑝re).

I am not sure if there's anything wrong with my R code given the data structure. Could you please take a look and help me with it.  

Thank you very much again!!

**R code**
out<-att_gt(yname="value",
            tname="month",
            idname="eci",
            gname="first.treated",
            xformla=~matchto,
            data=long2,
            control_group = c("nevertreated")
            
            )

summary(out)
ggdid(out)

**R results**
Group-Time Average Treatment Effects:
 Group Time  ATT(g,t) Std. Error [95% Pointwise  Conf. Band] 
     2    2 -283.8873   808.6093       -1783.307    1215.533 

**Data Setup of long2**
![image](https://github.com/user-attachments/assets/19eccf8c-91d2-4667-8584-f393cf03bd59)

**Comment by pedrohcgs** [comment]
When covariates are used, they will be different. Because the did package
will use a conditional parallel trends whereas the traditional estimator
relies on unconditional parallel trends.

If you remove the xformla argument, they should coincide

----------------------------------------------------
*Pedro H. C. Sant'Anna*
*https://psantanna.com <https://psantanna.com>*

----------------------------------------------------
Warning: This email may contain confidential or privileged information
intended only for the use of the individual or entity to whom it is
addressed. If you are not the intended recipient, please understand
that any disclosure, copying, distribution, or use of the contents
of this email is strictly prohibited.
----------------------------------------------------

**Comment by 49470952** [comment]
Hi Again,

By removing the covariate (see code below), the error message and the ATT value are exactly the same as the prior run.

No pre-treatment periods to test
> out<-att_gt(yname="value",
+             tname="month",
+             idname="eci",
+             gname="first.treated",
+             #xformla=~matchto,
+             data=long2,
+             control_group = c("nevertreated")
+             
+             )
No pre-treatment periods to test
> 
> summary(out)

Call:
att_gt(yname = "value", tname = "month", idname = "eci", gname = "first.treated", 
    data = long2, control_group = c("nevertreated"))

Reference: Callaway, Brantly and Pedro H.C. Sant'Anna.  "Difference-in-Differences with Multiple Time Periods." Journal of Econometrics, Vol. 225, No. 2, pp. 200-230, 2021. <https://doi.org/10.1016/j.jeconom.2020.12.001>, <https://arxiv.org/abs/1803.09015> 

Group-Time Average Treatment Effects:
 Group Time  ATT(g,t) Std. Error [95% Pointwise  Conf. Band] 
     2    2 -283.8873   793.0215       -1773.774    1205.999 
---
Signif. codes: `*' confidence band does not cover 0

Control Group:  Never Treated,  Anticipation Periods:  0
Estimation Method:  Doubly Robust

**Comment by pedrohcgs** [comment]
Can you send the data and the codes to my email address so I can check?

**Comment by 49470952** [comment]
What is your email address?

**Comment by pedrohcgs** [comment]
check my webpage

**Comment by 49470952** [comment]
Just before sending you the data, I double checked the DiD value our team calculated months ago and found out it was actually miscalculated. With the re-calculation, DiD is numerically the same as ATT now! However, adjusting for matching effect (matchto variable) or not, the overall ATT was not impacted. 

Thank you very much again for the big help!!! I really appreciate it.

**Comment by bcallaway11** [comment]
Not sure if this was fully resolved, but I don't think this is an issue with the did package, so closing.
