### ISSUE TITLE
Trouble understanding did with repeated cross-section data and individual-level treatment

### ISSUE THREAD

**Issue by barbarlo** [bcallaway11/did#201]
Hello,

I don't quite understand if it´s possible to use the did package with repeated cross sections and individual-level treatment. I explain myself with an example:

The data are repeated cross-sectional data for several years and the treatment is defined at the individual level (e.g. receipt of public aid). 
Within each year's cross section, I can only identify if individuals are treated that year, but not in earlier or later years. So all treated individuals will have a gname value equal to the year of observation and the untreated ones will have a value of 0 (but we can´t know if they are treated in earlier or later years).

In this context, is it possible to run did?

Thanks so much for your help.

**Comment by bcallaway11** [comment]
You are right that you are likely to run into issues here.  Let me just point you to the paper by Irene Botosaru and Federico Gutierrez that talks about these sort of issues: https://onlinelibrary.wiley.com/doi/full/10.1002/jae.2583?casa_token=9U5GAY_RwtoAAAAA%3AiWGZXh6d0cxZYDA-Dq2eaUzs1RkM4MKw0sUSMmEyRn7mQYKsr0u3aUEhg0eAYVm6tSdyvwgzQ92viltU1w

**Comment by barbarlo** [comment]
Thank you very much, I really appreciate your response.

I´m not an econometrician, just a practitioner so, after reading the paper, I guess that in my case with multiple time periods it´s much safer to try to get panel data : - )

Best regards and thanks a lot for your help in clarifying my doubts. 

Bárbara
