### ISSUE TITLE
Small feature request: increment Github version number to distinguish from CRAN

### ISSUE THREAD

**Issue by MatthieuStigler** [bcallaway11/did#208]
Currently, both the CRAN and Github development versions have the same number, which can make it difficult for a user to know whether they are using the CRAN (which contains critical bugs: https://github.com/bcallaway11/did/issues/191#issuecomment-2298491812) or Github version. 

Would it be possible to simply increment the Github version number in DESCRIPTION, possibly with `9000` following recommended practice (see https://bookdown.dongzhuoer.com/hadley/r-pkgs/description or https://github.com/tidyverse/dplyr/blob/main/DESCRIPTION)?

Thanks!

**Comment by pedrohcgs** [comment]
The description of the Github says that we are in version 2.2.0.903. The CRAN version is 2.1.2.
We just didn't create Github releases.

**Comment by MatthieuStigler** [comment]
upssss, I must have had a glitch in the matrix, even the github version came out with this number. Sorry for this misleading issue.
