### ISSUE TITLE
P-value for pre-test of parallel trends assumption not showing up

### ISSUE THREAD

**Issue by steph5050** [bcallaway11/did#211]
Hello, I am writing here because our code does not produce the p-value for pre-test of parallel trends assumption. The following is the att_gt code I used, using the state-year-month level dataset:

atts_notyet <- did::att_gt(yname = "outcome", 
                          tname = "yearmonth", 
                          idname = "state_fips", 
                          gname = "firstreat",
                          data = sy_noalways_age012_elig12, 
                          xformla = NULL,
                          alp=0.1,
                          allow_unbalanced_panel = TRUE,
                          clustervars = "state_fips",
                          est_method = "dr", 
                          control_group = "notyettreated", 
                          bstrap = TRUE, 
                          biters = 1000, 
                          print_details = TRUE, # if TRUE, print detailed results
                          panel = TRUE) 
summary(atts_notyet)

The output from this summary() command only shows ATT(g,t)'s without the p-value for pre-test of parallel trends assumption. Could you help me solve this issue?

Thank you very much!

**Comment by pedrohcgs** [comment]
Not sure how we are supposed to help here.

You can get the p-value of any point-estimate using t-stat (call it tval), and then using something like `2 * pnorm(abs(tval))`

If you want to test if all pre-treatment periods are zero, you can leverage the influence functions and conduct a Wald-test. 

However, we usually don't report p-values in our package. 

Thanks
