### ISSUE TITLE
Possible improvement for ggdid.R

### ISSUE THREAD

**Issue by kylebutts** [bcallaway11/did#25]
Within ggdid.R, you use `do.call("grid.arrange", c(mplots))`. The `grid.arrange` function creates a gtable which removes all of the ggplot functionality. 

The `ggarrange` function from the [ggpubr package](https://rpkgs.datanovia.com/ggpubr/reference/ggarrange.html) works very similar to grid.arrange, but instead keeps each group's ggplot editable/themeable. For example, if you want to put these plots in slides, it would be nice to be able to increase the font size or apply a consistent plot theme.

The only change in your code would be to add ggpubr and to replace `do.call("grid.arrange", c(mplots))` with `do.call("ggarrange", c(mplots, ncol= 1))`. This produces the exact same plot, but returns a list of ggplot objects which in turn can be modified.

**Comment by bcallaway11** [comment]
Thanks for suggesting this.  We have made this change; still doing a few tests, but this is likely to be in the next version of the code.
