### ISSUE TITLE
How to bin the distant relative period?

### ISSUE THREAD

**Issue by dayabin** [bcallaway11/did#28]
Hi Dr. Callaway, I wonder is there any way to bin the relative period by using the att_gt function? Say I am only interested in the relative period [-5, 5], and bin the distant periods < -5 and > 5 to -5 and 5, respectively. 

Another question is how can I introduce the trend variables, say state-specific trends, in att_gt function?

Thanks

**Comment by bcallaway11** [comment]
For binning the relative periods, we don't have this "out of the box", but here's an idea that should work.  You should be able to just run `att_gt` followed by `aggte(...,type="dynamic")`.  This will give you results at all relative times, but you can just drop the extra relative time periods.  [The only caveat to this is that if you use our uniform confidence bands, just dropping will lead to conservative (i.e., tend to be too wide) confidence bands, but I think this is unlikely to create a big issue]

I'm going to leave this issue open as we might add support for this at some point, but it is not going to be immediate.

For state-specific trends (I interpret this as individual-specific or unit-specific trends), we do not have this.  This is not really difference in differences.  I think it might be possible to "trick" our code into be useful in this case -- this paper might be helpful here: [Mora and Reggio (2019)](https://www.tandfonline.com/doi/abs/10.1080/07474938.2017.1348683) --  but I don't think we have any plans to incorporate this into our package.  It's not what I think you mean here, but just in case, our package will accommodate covariate-specific trends.

**Comment by pedrohcgs** [comment]
We are closing this since the `agge` function now allows one to select the relative time periods. We do not support binning, as that can lead to non-standard interpretations.
Thanks!

**Comment by pedrohcgs** [comment]
We are closing this since the agge function now allows one to select the relative time periods. We do not support binning, as that can lead to non-standard interpretations.
Thanks!
