### ISSUE TITLE
mp.spatt.test dosen't allow for xforumla to be NULL

### ISSUE THREAD

**Issue by ParkerWilliam** [bcallaway11/did#3]
The mp.spatt.test function dosen't seem to allow for xformula to be NULL. 

if you try to set the xformula in the example given in the package to NULL then it dosn't seem to do any calculations and just returns a empty object.  

`mptest <- mp.spatt.test(lemp ~ treat, xformla=NULL, data=mpdta,
                        panel=TRUE, first.treat.name="first.treat",
                        idname="countyreal", tname="year", clustervarlist=list(NULL))
summary(mptest[[1]])
`

**Comment by bcallaway11** [comment]
Try setting xformla=~1.  I think this should fix your problem.  But I'll update the code soon to have the same behavior when xformla is NULL.

**Comment by ParkerWilliam** [comment]
I will try and get back  to you.

**Comment by ParkerWilliam** [comment]
That doesn't work unfortunately.

**Comment by bcallaway11** [comment]
Here is something that will (I think) work:

`mptest <- mp.spatt.test(lemp ~ treat, xformlalist=list(~1), data=mpdta, panel=TRUE, first.treat.name="first.treat", idname="countyreal", tname="year", clustervarlist=list(NULL)) summary(mptest[[1]])`

That is, change `xformla` to `xformlalist` and adjust the argument slightly as well.

There was a bug in the example.  I don't think NULL will work currently, but I've adjusted the code and I'll have the github version updated soon and will make the update in the CRAN version at the next release.
