### ISSUE TITLE
ggdid is not working for "out" in the example

### ISSUE THREAD

**Issue by mmbanasaz** [bcallaway11/did#32]
ggdid(out, ylim=c(-.25,.1)) that you mentioned in your example does not work. 
the error is : could not find function "ggarrange"

**Comment by bcallaway11** [comment]
Ah, thanks for mentioning this.  I think this is actually a bug in our code.  I'll fix this, but pretty sure that you can get the code to work by adding the line:

`library(ggpubr)`

before you call `ggdid`

**Comment by mmbanasaz** [comment]
Yesss. It works. 
thanks
