### ISSUE TITLE
Relationship between `gname` and `tname`

### ISSUE THREAD

**Issue by amichuda** [bcallaway11/did#36]
hi! Thank you for the awesome package!

I had a quick question that I couldn't find in the documentation.

Does the group variable have to be in the same terms as the time variable? In your example, your `year` variable is in terms of years, and your `gname` variable is just an integer. Does `did` sort the years and map the number to the ordered list of unique dates? So is a treatment variable of 1 the first "post" observation?

**Comment by bcallaway11** [comment]
Thanks for the nice message.  The group variable should be in the same
units as the time variable.  So if time is in years, group should also be
in years.  The only caveat to this is the group should be set equal to 0
for units that never participate in the treatment.

Does that answer your question?

**Comment by amichuda** [comment]
Thank you for the quick reply!

Would this work if, for whatever reason, the time variable was a string? or does the time variable have to be datetime-like or a number?

**Comment by bcallaway11** [comment]
This is a good question.  I know for sure that we try to sort the time
variable at some point, but I'm not totally sure if that will cause the
code to crash.  I'd at least recommend being cautious.  Actually, unless
there something I'm missing, I'd recommend converting the string into some
kind of numeric value that makes sense before you pass it to our code.

**Comment by amichuda** [comment]
Thanks so much!
