### ISSUE TITLE
Parallel trends test

### ISSUE THREAD

**Issue by amichuda** [bcallaway11/did#37]
When getting results from `att_gt`, there is a parallel trends test statistic (pretty cool!). From what I understand, this is tested based off all pre-trend observations, is that correct?

As of now, I don't see a way to not do the pre-trends test when estimating. For situations for big data, it would be nice to be able to break up the different parts into separate function calls, so that I can run the parallel trends test (with `conditional_did_pretest`?) separately from the actual estimation of group-time average treatment effects. In this case, you can pass less data to `att_gt` as well.

Is it possible to run `att_gt` without running the parallel trends test?

**Comment by bcallaway11** [comment]
Hi amichuda,

It is not possible to run `att_gt` without the parallel trends test.  This version of the parallel trends test is unconditional; we are just testing if all the pre-treatment group-time average treatment effects are equal to 0.  In my experience, this is not a time-consuming part of the code to run.  That said, if you have a specific case where you think it is slowing things down, I'd be happy to take a closer look.

Brant
