### ISSUE TITLE
Feature Request: Allow for group-specific ATT(g,t) plots

### ISSUE THREAD

**Issue by pedrohcgs** [bcallaway11/did#40]
Sometimes, there are many groups, and plotting them all using ggdid may lead a clutter plot. It would be ideal to add an option to ggdid like "group", so users can visualize the group-specific event-study estimates.

**Comment by kylebutts** [comment]
Hope this helps!



    library(did)
    library(ggpubr)
    #> Loading required package: ggplot2
    data(mpdta)

    ggdid.MP <- function(object,
                         ylim=NULL,
                         xlab=NULL,
                         ylab=NULL,
                         title="Group",
                         xgap=1,
                         ncol=1,
                         legend=TRUE,
                         group=NULL,
                         ...) {
        
        mpobj <- object
        
        G <- length(unique(mpobj$group))
        Y <- length(unique(mpobj$t))## drop 1 period bc DID
        g <- unique(mpobj$group)[order(unique(mpobj$group))] ## -1 to drop control group
        y <- unique(mpobj$t)
        
        results <- data.frame(year=rep(y,G))
        results$group <- unlist(lapply(g, function(x) { rep(x, Y) }))
        results$att <- mpobj$att
        n <- mpobj$n
        results$att.se <- mpobj$se #sqrt(diag(mpobj$V)/n)
        results$post <- as.factor(1*(results$year >= results$group))
        results$year <- as.factor(results$year)
        results$c <- mpobj$c
        #vcovatt <- mpobj$V/n
        alp <- mpobj$alp
        
        
        mplots <- lapply(g, function(g) {
            # If group is not specified, plot all. If group is specified, only plot g in group
            if(is.null(group) | g %in% group) {
                thisdta <- subset(results, group==g)
                gplot(thisdta, ylim, xlab, ylab, title, xgap, legend)
            }
        })
        
        # Remove NULL
        mplots <- mplots[!sapply(mplots, is.null)]
        
        do.call("ggarrange", c(mplots, ncol=ncol))
    }

    out <- att_gt(yname = "lemp",
                  gname = "first.treat",
                  idname = "countyreal",
                  tname = "year",
                  xformla = ~1,
                  data = mpdta,
                  est_method = "reg"
    )

    ggdid(out)

![](https://i.imgur.com/4P0UDU3.png)

    ggdid(out, group = 2004)

![](https://i.imgur.com/aLuJ4E9.png)

    ggdid(out, group = c(2006, 2007))

![](https://i.imgur.com/fe33Hbg.png)

<sup>Created on 2021-03-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bcallaway11** [comment]
Thanks, Kyle.  I just added your code, and it will be available soon.  This is a good feature.

Brant
