### ISSUE TITLE
Aggregate ATT when there's no never-treated group

### ISSUE THREAD

**Issue by shoonlee** [bcallaway11/did#41]
Hi! Thanks for a great package!

I'm curious if users could use ```aggte``` function to get the overall ATT when there's no never-treated group or when a never-treated group is believed to be very different from the ever-treated group. I applied ```aggte``` for ```type = "group"``` after estimating ```att_gt``` with ```control_group = "notyettreated"``` after manually removing never-treated observations in the dataset. It returned ```ATT(g,t)``` for every ```g``` except for the last period (which returns NaN) and NaN for overall ATT. 

I understand that the package drops the last period and set units that do not become treated until the last period as the control group and thus the last ```ATT(g,t)``` will return NaN, but wouldn't it be useful to return overall ATT using ```ATT(g,t)``` from the rest of ```g```?

Thank you!

**Comment by bcallaway11** [comment]
Hi shoonlee,

Yes, I totally agree with what you are saying.  

However, when I try this, I don't seem to run into the problem that you are mentioning:

```
library(did)

data(mpdta)

# drop never treated
mpdta <- subset(mpdta, first.treat != 0)

no_untreated <- att_gt(yname="lemp",
                       idname="countyreal",
                       tname="year",
                       gname="first.treat",
                       data=mpdta,
                       control_group="notyettreated")

summary(aggte(no_untreated, type="group"))

Overall ATT:  
     ATT Std. Error     [95%  Conf. Int.] 
 -0.0114      0.016   -0.0427      0.0198 


Group Effects:
 group     ATT Std. Error [95% Simult.  Conf. Band]  
  2004 -0.0873     0.0278       -0.1459     -0.0287 *
  2006  0.0265     0.0187       -0.0130      0.0660  
---
Signif. codes: `*' confidence band does not cover 0

Control Group:  Not Yet Treated,  Anticipation Periods:  0
Estimation Method:  Doubly Robust
```
What's happening here is that the 2007 group (which would be available if we didn't drop the never-treated group) does not show up in the results, and the overall ATT is a weighted average of the two effects for groups 2004 and 2006.

Please feel free to follow up if I missed the point of your question or you are continuing to run into this sort of issue in your application.

Brant

**Comment by shoonlee** [comment]
Dear professor Callaway,

Thank you for your reply! I've compared my code to yours and I think I
found the issue in mine (thank you!). It was an error on my part, not on
the package itself.

However, while investigating, I found some weird results as well. But
before flagging this, I want to double-check a couple of things not to
waste your time. I'm writing this email to let you know that I'm taking
your reply seriously with many thanks, but it might take a couple of days
to actually leave a comment on Github. Thank you!

Best,
Seunghoon

**Comment by shoonlee** [comment]
Dear professor Callaway, 

Thank you so much for your reply. After comparing your code with mine, I could see where the issue came up. It was due to the specificity of my dataset, not an issue with the package. 

While further investigating the no never-treated group case, I noticed another issue. It produces different results depending on whether a panel is balanced or not, which does not happen when there are never-treated observations and when I use the default option for ```control_group```. Below is a reproducible example using ```mpdta``` data. 

From a practical point of view, when someone has to use not-yet-treated observations as a control group (i.e., no never-treated group), and if the dataset is unbalanced, should one first make the data balanced or not? As these two approaches produce different results, I was curious about what's recommended. Please let me know if the question is unclear. 

**When there's no never-treated obs**
````
library(did)
data(mpdta)
set.seed(910)
 
# Create an unbalanced panel
mpdta <- mpdta %>%
   mutate(row_id = runif(n = 2500)) %>% filter(row_id < 0.9) %>%
   group_by(countyreal) %>%
   mutate(n_ct = n())
 
 # It's now unbalanced
 table(mpdta$n_ct)
   2    3    4    5 
  14  132  672 1405 
 
# Keep observations that appear all periods
 mpdta_bal <- mpdta %>% filter(n_ct == 5)
 
# drop never treated from the unbalanced panel
 mpdta_no_untreated <- subset(mpdta, first.treat != 0)
 
# drop never treated from the balanced panel
 mpdta_bal_no_untreated <- subset(mpdta_bal, first.treat != 0)
 
 no_untreated <- att_gt(yname="lemp",
                        idname="countyreal",
                        tname="year",
                        gname="first.treat",
                        data=mpdta_no_untreated,
                        control_group="notyettreated")
 
 summary(aggte(no_untreated, type="group"))

Call:
aggte(MP = no_untreated, type = "group")

Reference: Callaway, Brantly and Pedro H.C. Sant'Anna.  "Difference-in-Differences with Multiple Time Periods." Forthcoming at the Journal of Econometrics <https://arxiv.org/abs/1803.09015>, 2020. 


Overall ATT:  
     ATT Std. Error     [95%  Conf. Int.] 
 -0.0328     0.0236    -0.079      0.0135 


Group Effects:
 Group Estimate Std. Error [95% Simult.  Conf. Band]  
  2004  -0.1469     0.0461       -0.2393     -0.0545 *
  2006   0.0191     0.0267       -0.0344      0.0727  
---
Signif. codes: `*' confidence band does not cover 0

Control Group:  Not Yet Treated,  Anticipation Periods:  0
Estimation Method:  Doubly Robust
 
 no_untreated_bal <- att_gt(yname="lemp",
                        idname="countyreal",
                        tname="year",
                        gname="first.treat",
                        data=mpdta_bal_no_untreated,
                        control_group="notyettreated")
 
 summary(aggte(no_untreated_bal, type="group"))

Call:
aggte(MP = no_untreated_bal, type = "group")

Reference: Callaway, Brantly and Pedro H.C. Sant'Anna.  "Difference-in-Differences with Multiple Time Periods." Forthcoming at the Journal of Econometrics <https://arxiv.org/abs/1803.09015>, 2020. 


Overall ATT:  
     ATT Std. Error     [95%  Conf. Int.] 
 -0.0318     0.0254   -0.0817       0.018 


Group Effects:
 Group Estimate Std. Error [95% Simult.  Conf. Band]  
  2004  -0.1491     0.0465       -0.2358     -0.0624 *
  2006   0.0299     0.0295       -0.0252      0.0850  
---
Signif. codes: `*' confidence band does not cover 0

Control Group:  Not Yet Treated,  Anticipation Periods:  0
Estimation Method:  Doubly Robust
````

**When there are no never-treated obs**
````
# Repeat the same exercise with data that has never treated group
 untreated <- att_gt(yname="lemp",
                        idname="countyreal",
                        tname="year",
                        gname="first.treat",
                        data=mpdta)
 
 summary(aggte(untreated, type="group"))

Call:
aggte(MP = untreated, type = "group")

Reference: Callaway, Brantly and Pedro H.C. Sant'Anna.  "Difference-in-Differences with Multiple Time Periods." Forthcoming at the Journal of Econometrics <https://arxiv.org/abs/1803.09015>, 2020. 


Overall ATT:  
     ATT Std. Error     [95%  Conf. Int.] 
 -0.0234     0.0183   -0.0593      0.0125 


Group Effects:
 Group Estimate Std. Error [95% Simult.  Conf. Band] 
  2004  -0.0995     0.0487       -0.1995      0.0006 
  2006  -0.0074     0.0250       -0.0588      0.0439 
  2007  -0.0171     0.0240       -0.0663      0.0322 
---
Signif. codes: `*' confidence band does not cover 0

Control Group:  Never Treated,  Anticipation Periods:  0
Estimation Method:  Doubly Robust
 
 untreated_bal <- att_gt(yname="lemp",
                     idname="countyreal",
                     tname="year",
                     gname="first.treat",
                     data=mpdta_bal)
 
 summary(aggte(untreated_bal, type="group"))

Call:
aggte(MP = untreated_bal, type = "group")

Reference: Callaway, Brantly and Pedro H.C. Sant'Anna.  "Difference-in-Differences with Multiple Time Periods." Forthcoming at the Journal of Econometrics <https://arxiv.org/abs/1803.09015>, 2020. 


Overall ATT:  
     ATT Std. Error     [95%  Conf. Int.] 
 -0.0234     0.0174   -0.0574      0.0106 


Group Effects:
 Group Estimate Std. Error [95% Simult.  Conf. Band] 
  2004  -0.0995     0.0496       -0.1990      0.0001 
  2006  -0.0074     0.0243       -0.0563      0.0414 
  2007  -0.0171     0.0253       -0.0679      0.0337 
---
Signif. codes: `*' confidence band does not cover 0

Control Group:  Never Treated,  Anticipation Periods:  0
Estimation Method:  Doubly Robust
````

**Comment by pedrohcgs** [comment]
Unless you set `allow_unbalanced_panel = TRUE`, the did package will balance the data. This matters because the comparison groups you are using differ.

Without knowing the specifics, I would say that you should probably consider setting  `allow_unbalanced_panel = TRUE`.
