### ISSUE TITLE
att_gt seems to break with too many columns

### ISSUE THREAD

**Issue by azdrojew** [bcallaway11/did#42]
I attempted to run att_gt on a dataset with ~40 columns and it would return an error message, but it wasn't clear to me what the issue was. It seems to occur around the "if (panel)" line in the compute.att_gt function. Anyways, it took me a day or so to troubleshoot the issue, but when I gave the function only the 4 columns it needs to run, it ran perfectly. So maybe an error message saying "You have included too many columns" would save people some time. Or maybe the code can be updated to narrow them down automatically. Otherwise a great companion package to a great paper!

**Comment by pedrohcgs** [comment]
I do not really follow. Can you post a reproducible example where the error appears?

**Comment by azdrojew** [comment]
Actually I think the number of the columns isn't the problem. I think coincidentally the name of one of my columns must be interfering with the function. After troubleshooting, it runs fine as long as I remove a column named "t1". A weird coincidence but  I think the function must use t1 for something else - does that sound right?

**Comment by pedrohcgs** [comment]
We use t1 as argument for functions in the aggte, but that should not interfere here. Let me know if you can send a reproducible sample code with the issue.

**Comment by azdrojew** [comment]
Here is a reproduction:

## It works with mpdta
data(mpdta)
out <- att_gt(yname = "lemp",
              gname = "first.treat",
              idname = "countyreal",
              tname = "year",
              xformla = ~1,
              data = mpdta,
              est_method = "reg",
              control_group="notyettreated"
)

## After adding "t1" column, it stops working:

mpdta$t1 <- 1

out <- att_gt(yname = "lemp",
              gname = "first.treat",
              idname = "countyreal",
              tname = "year",
              xformla = ~1,
              data = mpdta,
              est_method = "reg",
              control_group="notyettreated"
)

It looks like BMisc::panel2cs uses t1 in the function (https://rdrr.io/cran/BMisc/src/R/BMisc.R), so I think that was the source of the issue

**Comment by pedrohcgs** [comment]
Good catch. Let us see how we can fix this.
Thanks!

**Comment by bcallaway11** [comment]
This is fixed now (in version 2.1)!
