### ISSUE TITLE
Expose setup_sim.R

### ISSUE THREAD

**Issue by grantmcdermott** [bcallaway11/did#44]
Just following on from a quick chat with @pedrohcgs. The vignettes should expose [`setup_sims.R`](https://github.com/bcallaway11/did/blob/master/vignettes/setup_sims.R) (or at least point users to it), or else functions like `build_sim_dataset()` won't work for ppl following the examples.

**Update.** Probably unnecessary, but reprex following the [Getting Started](https://bcallaway11.github.io/did/articles/did-basics.html) vignette:

``` r
library(did)

# set seed so everything is reproducible
set.seed(1814)

# generate dataset with 4 time periods
time.periods <- 4

# add dynamic effects
te.e <- 1:time.periods

# generate data set with these parameters
# here, we dropped all units who are treated in time period 1 as they do not help us recover ATT(g,t)'s.
dta <- build_sim_dataset()
#> Error in build_sim_dataset(): could not find function "build_sim_dataset"
```

<sup>Created on 2021-03-30 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by bcallaway11** [comment]
Hi Grant,

Yes, you are definitely right here.  Those functions are hacked together, basically just originally intended for testing our code, but we also found them helpful to write up the documentation.  This is on my TODO list now (I'll leave the issue open) to make it accessible (and less of a mess), but, in the meantime, you can find it here:  https://github.com/bcallaway11/did/blob/master/tests/setup_sims.R

Brant

**Comment by bcallaway11** [comment]
Functions related to simulating data are now available.

**Comment by grantmcdermott** [comment]
Thanks Brantly. 

As an aside, the new speed improvements look fantastic. I'm just getting back from vacation, but looking forward to giving them a spin. Congrats on the new release.

**Comment by bcallaway11** [comment]
Thanks, Grant.  Keep me posted!
