### ISSUE TITLE
Confidence interval text incorrect, and partial name match, in summary.AGGTEobj

### ISSUE THREAD

**Issue by NickCH-K** [bcallaway11/did#47]
In `summary.AGGTEobj()`, the column header for the confidence interval has 95% hard-coded in and will say it's a 95% interval regardless of the actual value of `alp`.

Also, lines 114 and 115:
```r
cband_lower <- object$att - object$crit.val.egt*object$se.egt
cband_upper <- object$att + object$crit.val.egt*object$se.egt
```

find `$att` by partial name match, which doesn't work in all contexts. These should be `object$att.egt`

**Comment by pedrohcgs** [comment]
Thanks Nick! Fixing this right now!
