### ISSUE TITLE
Question about time-varing covariates 

### ISSUE THREAD

**Issue by JaeMan71** [bcallaway11/did#49]
Sorry for asking the questions frequently.
I am writing a paper for estimating the effect of the mandatory face-covering policy for COVID-19.

Each state enacted a mask covering order on different dates, and some states did not pass it. Therefore, I want to estimate how the policy affects COVID-19 new cases and deaths.

However, while I want to check the mask policy effect, the states enacted various social distance COVID-19 policies, such as large gathering ban, restaurant limit, stay-at-home order, COVID-19 vaccination, etc. So, I made dummy variables for the policies to control the policies and number of people who got vaccinated.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/76572796/114334485-a550fa00-9b18-11eb-90ac-67c2a6ac59b0.png">
The head shows the simple dataset of the total.
BSNS is a closed non-essential business, 
CLNURSHM is date-banned visitors to nursing homes, stay home is begging date of stay at home order, 
emergency is the date of announcing state emergency. CLSCHOOL is the date of closing public schools. daily_vaccination is the number of people who got covid vaccination.
For example, in Georgia state, the closing public school was from Mar 10th to Sep 1st. The dummy variable will be 1 from 20200310 to 20200901, and the other date is 0.
Also, population, adult risk share variables are time-invariant covariate.

> 

In this regard, may I ask if there is a way to put those time-varying covariates in your DID package in R?
I know did package sets the value of the covariate to be equal to the value of the covariate in the first time period. So, I don't know whether I can put those time-varying covariates just in xformla = ~ population+adu_risk_share+Emergency+CLSCHOOL+BSNS+ CLNURSHM +STAYHOME+daily_vaccinations 
to control time-varying covariates.

Another question is when I use est_method="dr" or est_method="reg",
<img width="392" alt="image" src="https://user-images.githubusercontent.com/76572796/114334560-c7e31300-9b18-11eb-9abd-e6b422ec4746.png">

Error in DRDID::reg_did_rc(y = Y, post = post, D = G, covariates = covariates,  : 
  Outcome regression model coefficients have NA components.
Error in DRDID::drdid_rc(y = Y, post = post, D = G, covariates = covariates,  : 
  Propensity score model coefficients have NA components.
These error codes appear. I guess the reason is because of those policy dummy variables.
However, I don’t know how to handle this error.

This is my code for did.
xample_attgt<-att_gt(
  yname = "new_case",
  tname = "submission_date",
  idname = "State_code",
  gname = "First_treat",
  xformla = ~adu_risk_share+population+stay+Emergency+CLSCHOOL+BSNS+CLNURSHM+STAYHOME+daily_vaccinations,
data = mask_5,
  panel = TRUE,
  allow_unbalanced_panel = TRUE,
  control_group = c("nevertreated", "notyettreated"),
  anticipation = 0,
  weightsname = NULL,
  alp = 0.05,
  bstrap = FALSE,
  cband = TRUE,
  biters = 1000,
  est_method="dr",
  clustervars = NULL,
  print_details = FALSE,
  pl = FALSE,
cores = 1)

I am looking forward to hearing from you.
 
Best Regards,
Jae Man Park

**Comment by pedrohcgs** [comment]
As as I can tell, those dummy variables are not really "covariates", as they are policy themselves. You are getting overlap issues essentially because of that. This is more like a design problem, not a package problem. 

Thanks
