### ISSUE TITLE
error in mp.spatt function

### ISSUE THREAD

**Issue by caiy0233** [bcallaway11/did#5]
Hi Thanks for creating this package! When I run the mp.spatt() function and see it gives all the "current period" and "current group", there emerges an error that "Error in split.default(att, group) : 
  group length is 0 but data length > 0. " Would you mind suggesting the possible reason for that? Thanks a lot!

code:
out<-mp.spatt(median_income ~ treatment, data=income1, panel=TRUE, first.treat.name="enteryear", idname="cityst",  tname="year", bstrap=FALSE, se=TRUE, cband=FALSE)

dataset:
![image](https://user-images.githubusercontent.com/43733133/57997846-751b9080-7a94-11e9-9329-86788d575575.png)

**Comment by bcallaway11** [comment]
Hi -- I think this sort of error is related to some small "groups".  Try figuring out which groups, here defined by 'enteryear', do not have many observations and try dropping those.

We also have some improved handling of these types of problems in the development version of the package.  You can try it with

devtools::install_github("bcallaway11/did")

Please let me know if that helps.

**Comment by caiy0233** [comment]
Hi, Thanks a lot for your helpful advice! I only removed the rows whose "enteryear" is 2017, which is the latest year in both "year" and "enteryear" and the error is solved.

![image](https://user-images.githubusercontent.com/43733133/58042337-0d9b2a80-7b00-11e9-90bf-60e2eede04ca.png)
