### ISSUE TITLE
Streamlining the ggdid function for improved usability and look

### ISSUE THREAD

**Issue by NickCH-K** [bcallaway11/did#50]
Was looking through the `ggdid` code as I set up the Stata port. Some things pop out:

1. The `ggplot2::guides()` function can be used to remove the legend instead of `ggpubr::rremove()`, which as far as I can tell would allow the **ggpubr** dependency to be dropped
2. The vertical/horizontal gridlines in the background make the CIs hard to see, these can be removed with `+theme(panel.grid.major.x = element_blank(),panel.grid.minor.x = element_blank())` to get rid of vertical, the same code but with `y` instead of `x` for horizontal, or `+theme(panel.grid = element_blank())` to remove them all. (Alternately, you could keep the **ggpubr** dependency and use `ggpubr::theme_pubr() + theme(legend.position = 'right')` instead of `theme_bw()`, which would also accomplish this and look nice in a few other ways). Alternately, there are a few different ways to remove all the grid lines but keep them at `0` so you can see whether your CI crosses 0.
3. The use of `ggarrange()` in `ggdid.MP()` to combine the graphs makes it impossible to change any theming after the fact. The use of **ggplot2**'s built-in faceting system with `facet_wrap()` would return a regular-ol' **ggplot** object that could be edited by the user after the fact in all the normal ways.
4. My understanding is that it's generally frowned upon for packages to do their own **ggplot2** theming, and you're "supposed" to return an unthemed object for the user to do any decoration on themselves. I think that's a bit silly, but one half-measure on this would be to add a `theme` option to `ggdid()` (and the functions it calls) that defaults to `TRUE`, and if you set it to `FALSE`, it skips all the theming.

I'd be happy to make these changes and do a PR (for this and the other issues I've added in the process of making the Stata package) if they sound good to you. I understand some of these proposals are subjective.

**Comment by NickCH-K** [comment]
This is what the `ggpubr::theme_pubr()` version would look like

![image](https://user-images.githubusercontent.com/44816781/114461822-133c0680-9b97-11eb-8de3-d4587b4d1d39.png)

**Comment by pedrohcgs** [comment]
Please do it! I like it with the marker at 0 (as default)

**Comment by NickCH-K** [comment]
Great! I will work on this.
