### ISSUE TITLE
Issue installation

### ISSUE THREAD

**Issue by leonschmidt93** [bcallaway11/did#51]
Hello, 

Thanks for providing this great package!

I am having an issue regarding the installation. I opened R (for the first time) and typed into the console your command for the installation

install.packages("did")

R starts the installation but after a while it always gets stuck and displays this message 

trying URL 'https://ftp.gwdg.de/pub/misc/cran/bin/windows/contrib/4.0/did_2.0.0.zip'
Content type 'application/zip' length 886157 bytes (865 KB)
downloaded 865 KB

The installation does not go further. Do you happen to know how to solve this?

The same issue occurs if I specify the alternative command to install the newest version.

Thanks a lot!

Leon

**Comment by pedrohcgs** [comment]
Try these commands:
`install.packages("devtools", dependencies = TRUE)
devtools::install_github("bcallaway11/did",  dependencies = TRUE)`

Let me know if this works.

**Comment by leonschmidt93** [comment]
Thanks a lot for your quick help, that worked!
