### ISSUE TITLE
Specifying control variables for outcome model with doubly robust estimator

### ISSUE THREAD

**Issue by SabineLa** [bcallaway11/did#52]
Thanks for this great package!

I have a question regarding the doubly robust estimator: How can I specify the outcome model when using the doubly robust estimator?

I’m using the att_gt function with the doubly robust estimator and covariates. The covariates are used in the propensity score model. But I wonder whether and how I can add control variables for the outcome model? Is there any option to include additional control variables within the package yet?

Many thanks for your reply!

**Comment by pedrohcgs** [comment]
Same variables that enter the propensity score, enters the outcome regression model for the evolution of untreated units.
