### ISSUE TITLE
Drop NAs in X vars

### ISSUE THREAD

**Issue by kylebutts** [bcallaway11/did#55]
Is it possible to have att_gt automatically drop units with NAs for X vars? Currently the function will not run. Reprex below:

    library(tidyverse)
    library(did)
    data(mpdta)
    out <- att_gt(yname = "lemp",
                  gname = "first.treat",
                  idname = "countyreal",
                  tname = "year",
                  xformla = ~lpop,
                  data = mpdta,
                  est_method = "reg",
                  control_group="notyettreated"
    )
    out
    #> 
    #> Call:
    #> att_gt(yname = "lemp", tname = "year", idname = "countyreal", 
    #>     gname = "first.treat", xformla = ~lpop, data = mpdta, control_group = "notyettreated", 
    #>     est_method = "reg")
    #> 
    #> Reference: Callaway, Brantly and Pedro H.C. Sant'Anna.  "Difference-in-Differences with Multiple Time Periods." Forthcoming at the Journal of Econometrics <https://arxiv.org/abs/1803.09015>, 2020. 
    #> 
    #> Group-Time Average Treatment Effects:
    #>  Group Time ATT(g,t) Std. Error [95% Simult.  Conf. Band]  
    #>   2004 2004  -0.0212     0.0228       -0.0819      0.0394  
    #>   2004 2005  -0.0818     0.0269       -0.1533     -0.0104 *
    #>   2004 2006  -0.1385     0.0372       -0.2373     -0.0396 *
    #>   2004 2007  -0.1075     0.0327       -0.1945     -0.0206 *
    #>   2006 2004  -0.0081     0.0235       -0.0707      0.0545  
    #>   2006 2005  -0.0062     0.0192       -0.0573      0.0449  
    #>   2006 2006   0.0094     0.0171       -0.0362      0.0549  
    #>   2006 2007  -0.0415     0.0207       -0.0965      0.0134  
    #>   2007 2004   0.0267     0.0150       -0.0133      0.0667  
    #>   2007 2005  -0.0043     0.0155       -0.0455      0.0370  
    #>   2007 2006  -0.0285     0.0170       -0.0737      0.0167  
    #>   2007 2007  -0.0288     0.0163       -0.0722      0.0146  
    #> ---
    #> Signif. codes: `*' confidence band does not cover 0
    #> 
    #> P-value for pre-test of parallel trends assumption:  0.23014
    #> Control Group:  Not Yet Treated,  Anticipation Periods:  0
    #> Estimation Method:  Outcome Regression

    mpdta[1, "lpop"] <- NA
    out <- att_gt(yname = "lemp",
                  gname = "first.treat",
                  idname = "countyreal",
                  tname = "year",
                  xformla = ~lpop,
                  data = mpdta,
                  est_method = "reg",
                  control_group="notyettreated"
    )
    #> Error in data.frame(..., check.names = FALSE): arguments imply differing number of rows: 2500, 2499

<sup>Created on 2021-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by bcallaway11** [comment]
Well, in principle, we could probably do this (and that error message does seem cryptic), but I feel better about users dropping their own missing values (and making sure they are good with it).  That said, we do balance the panel for you, so adding the following line right before the call to `att_gt` will get the code running again:

`mpdta <- mpdta[complete.cases(mpdta),]`

**Comment by bcallaway11** [comment]
I'm going to leave this open for now, but with the only goal of giving a reasonable error message for this case, not with making the code run when they are missing values for important variables

**Comment by kylebutts** [comment]
Re: reasonable error messages, this package or assertthat by Hadley Wickham can do a lot of work for y’all on informative error messages:

https://journal.r-project.org/archive/2017/RJ-2017-028/RJ-2017-028.pdf

**Comment by adonina** [comment]
Hi..I have almost the same question (or at least related).

The story is: 
Y - employment status of woman.
X - age, partner dummy, number of children etc.

I would like to also include as covariates: child_age, age of spouse, spouse's income and other relatives' characteristics.

But for a woman who doesn't have a child or husband the values for the above-mentioned variables would be NA.

So I do have dummy variable partner = {1,0}, but NA's in "spouse age" variable for single woman - do not allow me to include this regressor into the model.
I get the "arguments imply differing number of rows: "

Is there any option for how this issue could be solved?
I don't get how to compare not only married/single women, but estimate the effect of a husband's/child's age on woman's employment status.
If I use only complete observations for all interesting for me variables - I lose all single and all childless individuals.
If I include childless and single persons - I have to reduce the list of covariates.

Thanks in advance for any suggestions.

**Comment by bcallaway11** [comment]
This one is fixed.  We don't error now with missing covariates, but warn that we are dropping these rows.  Here is an update to @kylebutts example.

``` r
library(did)
data(mpdta, package="did")

mpdta[1, "lpop"] <- NA
out <- att_gt(yname = "lemp",
              gname = "first.treat",
              idname = "countyreal",
              tname = "year",
              xformla = ~lpop,
              data = mpdta,
              est_method = "reg",
              control_group="notyettreated"
              )
#> Warning in pre_process_did(yname = yname, tname = tname, idname = idname, :
#> dropped 1 rows from original data due to missing data
#> Warning in pre_process_did(yname = yname, tname = tname, idname = idname, :
#> Dropped 1 observations while converting to balanced panel.
```
