### ISSUE TITLE
P-value for pre-test of parallel trends assumption

### ISSUE THREAD

**Issue by gabydeschamps** [bcallaway11/did#58]
Would it be possible to add a feature to control the length for which to do the pre-test? I have many time periods so I would like to do the pre-test for parallel trends for periods closer to the reform implementation. and not all periods before the implementation.

Thanks in advance!

**Comment by bcallaway11** [comment]
This is something we will think about adding. In the meantime, you can definitely compute this sort of pre-test using the available output from the code.  I'm pasting in some code below that will do this sort of test for the closest few periods to the treatment using the output of our code with data provided in the package, but I think it should just be a minor tweak to get it to work in another application.  [Our code outputs the influence function for all the ATT(g,t)'s so this type of thing is not too difficult].

```
library(did)
data(mpdta)

out <- att_gt(yname = "lemp",
              gname = "first.treat",
              idname = "countyreal",
              tname = "year",
              xformla = ~lpop,
              data = mpdta,
              control_group="notyettreated"
              )

# available event times
e <- out$t - out$group
# show that these range from -3 to 3
sort(unique(e))

# let's say you only want to test in two
# periods closest to treatment
# you can adapt this line to however many periods before
# treatment that you want to include
which_e_to_test <- e %in% c(-1,-2)

# pick up attgt in those periods
att_e_to_test <- out$att[which_e_to_test]

# pick up corresponding columns in influence function
test_inffunc <- as.matrix(out$inffunc[,which_e_to_test])

# put everything together to come up with a Wald test
n <- nrow(test_inffunc)
V_e <- t(test_inffunc)%*%test_inffunc/n

# wald test
W_e <- n*( t(att_e_to_test) %*% solve(V_e) %*% att_e_to_test)
# degrees of freedom
q <- length(att_e_to_test)
# p-value
W_e_pval <- 1-pchisq(W_e,q)

# can see that we don't reject here
W_e_pval
```

Hope this helps, and I can help more if parts of this are unclear.

Brant

**Comment by gabydeschamps** [comment]
Thanks for the quick reply. This is extremely useful, thank you so much!
