### ISSUE TITLE
Dummies as covariates, warnings glm.fit: prob num 0 or 1, and DDD

### ISSUE THREAD

**Issue by KarolinaHelena** [bcallaway11/did#59]
Hi,

Thanks for a great package, I'm using it after having read Callaway and Sant'Anna (2020) article, which is also great! 

I'm using the did package for a staggered DD analysis, in which I would like to include covariates. I'm a little new to all this, so I'm sorry if my question is rather basic or if this is the incorrect place to ask it. 

If I do the following command, I get this error: "Error in solve.default(crossprod(wols.x.post.treat, int.cov)/n) : Lapack routine dgesv: system is exactly singular: U[2,2] = 0"

I believe this happens when I include covariates which are dummies (describing the type of municipality (urban, rural, etc)), as I do not get any error if I run it without them. Is there a way to include time invariant dummies as covariates when doing the dr estimation? 

```
mort70.2 <- att_gt(yname = "mortality70",
                   tname = "year",
                   idname = "muncode",
                   gname = "adoptionyear",
                   xformla = ~ lnetincome65 + shareunied + shareprivateemp  + shareimmigrants65plus + leftmajority +     Kommungruppkod + sharepopabove65 + ltotpop + populationpersqkilometer ,
                   data=Data,
                   panel=TRUE,
                   control_group="nevertreated",
                   bstrap=TRUE, #this has to be set when clusters happen
                   clustervars="muncode",
                   est_method = "dr")
```

When I do the above command but excluding the dummy variables, I get the following error: "Error in solve.default(crossprod(wols.x.pre.treat, int.cov)/n) : system is computationally singular: reciprocal condition number = 9.25539e-20" and also this warning (which I get multiple times): "glm.fit: fitted probabilities numerically 0 or 1 occurred "

I have tried removing some of the covariates which are highly correlated, and it stops giving me the error. But the warning  "glm.fit: fitted probabilities numerically 0 or 1 occurred" remains until I have removed all but three of the covariates. As the group that at some point receives treatment is quite different from the ones that never do, I have also tried using the "not yet treated" and the dr estimation method. Then warnings: "glm.fit: fitted probabilities numerically 0 or 1 occurred"  remains and I also get the warning that the overlap condition is violated for one of the treatment groups for a bunch (but not all) of the post treatment years.  

When I use the reg estimation method instead, it does not give me any warnings and I can include all covariates, including the dummies. So I have two questions regarding this. First, does the dr estimation give me the glm.fit warning because it perfectly predicts whether a municipality is in the treatment group or not? Second question (which is something maybe just up to what I believe is best for my study and data, but I feel it is worth asking as I am rather new at this) is whether from this it seems that the reg estimation method works better for me than the dr estimation method? 

Another question I have is whether it is possible to do a difference-in-difference-in-difference (DDD) using this package. Basically, I'm looking at mortality rates and the policy I am investigating will impact those 70 years and above, so I would like to use the age group 60-69 as an internal control. Could this be included in the did command somehow? 

So just to summarise my questions, is it possible to include dummy variables as covariates when using the DR estimation method? Does the issues I have with including covariates in the dr estimation put me in favour of using the reg estimation? And is it possible to include internal controls in some type of DDD estimation in the did package? 

I hope I was clear enough, happy to provide more info if needed!

**Comment by bcallaway11** [comment]
Thanks for the message.  Yes, I think this sort of issue is pretty common and relates to group sizes and the number of covariates in the model.

Let me give you a couple of quick explanations:
* The doubly robust estimates and inverse propensity score methods involve estimating the propensity score, and this is where these warnings are coming from.  The warnings about overlap conditions being violated are more serious than the ones about propensity scores being numerically equal to 0 or 1 as our approach needs propensity scores < 1, but close to 0 is ok (basically this is ensuring that among all treated units, we can find a “match” from the comparison group with the same characteristics).  The error about `solve.default(...` I am not exactly what is going on here.  
* The regression method just estimates a regression for the comparison group, so, especially if this group is bigger, this may run without any issues/warnings.

About triple differences, we don’t have this available.  I’m not really an expert here, but I think this is sort of like using our code for one particular subgroup (e.g., based on age) and then another subgroup and taking the difference in the estimated ATT(g,t) between the two subgroups.  If that’s right, I think you could make progress on this front building off of our code, but I’m not totally sure.  I’ll tag @pedrohcgs here, and perhaps he will have some ideas.

If you want me to take a closer look at your data & code, you can send me an email (Brantly.callaway@uga.edu), and I’d be happy to try to help more there.  I’ll probably be slow to reply the rest of today, but will be available again tomorrow.

Brant

**Comment by KarolinaHelena** [comment]
Thank you! 

Okay I understand it better now. But I still have the overlap condition issue. It would be great if you could look at them, I will email them now!

**Comment by bcallaway11** [comment]
Some notes to self on this one:
* I have code for tracking this after the fact, but we should strongly consider returning a list of observation ids where overlap condition is violated, so that user can potentially easily drop these to recompute $ATT(g,t)$ without using these observations.

**Comment by bcallaway11** [comment]
I added the function `trimmer` to the `did` package.  It's helpful for detecting observations where overlap condition is violated.
