### ISSUE TITLE
Error when estimating event-studies effects

### ISSUE THREAD

**Issue by IrinaZai** [bcallaway11/did#61]
Starting today I receive the following message when estimating the dynamic (event-study) effects. Yesterday there were no issues like this using the same data and same code:

`output1_es = aggte(output1, type = "dynamic", na.rm = TRUE)`

Error:
`Error in group + max_e : non-numeric argument to binary operator`

**Comment by bcallaway11** [comment]
Hi Irina,

Thanks for the message.  Would you mind sending me a way to replicate this error?  You can email me at brantly.callaway@uga.edu

Brant
