### ISSUE TITLE
Incorrect number of dimensions

### ISSUE THREAD

**Issue by lucianacosta23** [bcallaway11/did#62]
Dear Callaway and Sant'Anna,
first of all, thank you for this great package!
I'm working with a balanced panel (265,440 obs = 3160 municipalities over 84 months). There are no missings in the dataset. My group variable and time variable are in the same unit, and the group variable is set to zero for the never treated group. 

When running the code below (after calling the data) with the full dataset, I get the following message: "Error in data[, tname] : Incorrect number of dimensions". 

out <- att_gt(yname = "credpc",
              gname = "firstdata4g",
              idname = "mun",
              tname = "datanew",
              xformla = ~1,
              data = banco,
              est_method = "reg"
)

However, if I keep in the dataset only the variables needed to run the code above (without any covariate), the code works fine. Would you have any advice or suggestions? 
Sorry in advance if I wasn't clear. Thanks a lot!
Luciana

**Comment by bcallaway11** [comment]
Hi Luciana,

Thanks for the message.  It doesn't seem to me like you are doing anything wrong, so I'm not sure how you are getting this error.  If it is possible, could you send me your data (or possibly a subset of it) and code that will reproduce the error that you are getting.  My email address is brantly.callaway@uga.edu

Brant

**Comment by apodges** [comment]
What was the cause of this issue? I am also encountering it. I think it may be because I only have two units that are treated, both of which occur at two different time periods.
