### ISSUE TITLE
Any way to include time-varying covariates?

### ISSUE THREAD

**Issue by duncanhobbs** [bcallaway11/did#65]
I am working on a project examining effects of state-level minimum wage changes.

In the standard DiD regressions I am running, I include time-varying covariates like annual state per capita income and an index of state house prices to control for economic factors at the state level that could affect employment other than the minimum wage.

I read that the package expects covariates to be time-invariant, and it sets the value of the time-varying covariate to be equal to the value of the covariate in the first time period.

1) Is this time period the first time period in the sample or the first period when a unit is treated?

2) Is it possible to include the level of a time-varying covariate like per capita income each period as a separate covariate or would this not work?

**Comment by bcallaway11** [comment]
Hi Duncan,

Thanks for the message.  I think our documentation is a little off here.

For time varying covariates, we include their value in the period right before a unit becomes treated.  For example, with minimum wage, if a state increases its minimum wage in, say, 2005, (and you include per capita income as a covariate, we would use the value of per capita income in 2004 as the covariate in all post-treatment periods.

The one caveat to this is if you estimate effect in pre-treatment periods (usually in order for a pre-test of parallel trends).  In that case, we would use the value of the covariate in the period right before.  So, if you estimate pre-treatment effects of minimum wage, say, effects in 2003 for a state treated in 2005, we would include the value of per capita income from 2002.

For the second question, in principal you could do this (in my view, there are potentially some drawbacks here), but our code uses the approach above with time varying covariates.

Hope this helps.  Feel free to follow up.

Brant

**Comment by duncanhobbs** [comment]
Thanks! 

I am a research assistant and was asked to implement this for a project using ACS microdata.

I tried reading through your paper to better understand what the package does

You can't explicitly include time-varying covariates, but when you include covariates in the model, this conditions the probability of being treated by time g on these covariates.

And the covariate-specific trends for all units treated at time g are the same in all post-treatment periods,, but there is no similar  assumption about pretreatment trends.

This is looser than the assumptions for TWFE which require that the effects of covariates on the treated and control observations be the same and that there are no differential trends in time-varying covariates between treatment and control groups.

Is this correct?

**Comment by bcallaway11** [comment]
Yes, I think this is basically right.  TWFE is going to be more reliant on the linear functional form for the covariates being correct which is related to what you mention here.
