### ISSUE TITLE
Error in package install

### ISSUE THREAD

**Issue by Kwill147** [bcallaway11/did#67]
Thank you for a great package. When I install the package and try to run the att_gt function, I get an error message.

Error in loadNamespace(name) : there is no package called ‘DRDID’

I tried loading directly from Github but get the same issue. Is there a workaround for this?

Error message for GitHub install:
ERROR: dependency ‘DRDID’ is not available for package ‘did’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/did’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/ts/sjchzxws09bg9nnmf62z3flr0000gn/T//Rtmpu0x02q/fileac15120bebc/did_2.0.1.908.tar.gz’ had non-zero exit status

**Comment by Kwill147** [comment]
I had a lower version of R. I needed to update the R to 4.0 or higher. This resolved the issue.

**Comment by bcallaway11** [comment]
That makes sense.  I was actually just typing you a message when I saw your new comment.  Glad this worked.

Brant
