### ISSUE TITLE
Making att_gt to run faster

### ISSUE THREAD

**Issue by antrologos** [bcallaway11/did#70]
Hi Brantly and Pedro,

I've noticed that `att_gt` creates a copy of the entire dataset (located at .$DIDparams$data) and returns it as output. If the dataset is large (e.g. > million rows and 200+ columns), this makes `pre_process_did` to run very slowly -- and sometimes to halt due lack of memory. However, this issue is drastically diminished when I pass only the columns I will actually use in the model. 

I was wondering if it would be possible to keep only the variable that are actually part of the model.matrix and/or auxiliariary to the model (sampling weights, cluster variable etc) as in `lm` and other similar functions

**Comment by bcallaway11** [comment]
Hi Rogerio,

This is a good idea.  I'm going to leave this issue open and (hopefully) make some progress on it the next big push to the `did` package.

Brant

**Comment by bcallaway11** [comment]
Hi Rogerio,

The new version of our code (which should be headed to CRAN in the next day or two) is much more memory efficient.  If you try it out, please keep me posted on how it goes.

Brant
