### ISSUE TITLE
Time varying covariates

### ISSUE THREAD

**Issue by DimExa** [bcallaway11/did#71]
Dear Callaway and Sant'Anna,
First of all, thank you for the great package!

In my setup I have a balanced panel of about 25,000 firms operating in the period 2009-2017. I made it balanced on my own by dropping all missing observations. Also I dropped the cases where the first treatment occurs at the first year of the panel (In my case, 2009). I run the model in the following way:

out <- att_gt(yname = "log_m_share",
              gname = "first_treat",
              idname = "firm_id",
              tname = "year",
              xformla = ~log_capital_intensity + log_l + log_age + as.factor(sector_FE) + as.factor(region_FE),
              data = dat,
              clustervars = "firm_id",
              alp = 0.05
)

where log_capital_intensity + log_l + log_age are all time-varying variables and sector_FE, region_FE are sector and regional categorical variables respectively.
In the vignette I read that:
"The did package requires that covariates be time-invariant. For time varying covariates like county population, the did package sets the value of the covariate to be equal to the value of the covariate in the first time period."

So, I assume that for the three time-varying covariates above, the package automatically considers the values of the first year in my panel (in that case, the value for 2009). The code runs without problems.
However, I wanted to validate whether the package indeed considered the values of 2009 as pre-treatment covariates, so I replaced these three columns with time-invariant columns having for each year, their values in 2009 and I got different results.

Moreover, I looked at your application and I see that county population is not time-invariant in your case, so I got a bit confused there.

I am also new to R, so basically I have two questions:
(i) Which is the correct way to represent time-varying covariates? Leaving them to be time-varying (where the values change every year within firm) or replace all cells with value of 2009?
(ii) Is it fine to define sector and regional categoricals as I did above (with the as.factor() command)?

Thank you in advance.
Dimitris

**Comment by bcallaway11** [comment]
Hi Dimitris,

Good question.  That vignette is not 100% correct.  For time varying covariates, the ‘did’ package takes their value in a “base period” which, in post-treatment time periods, is just the period right before the treatment takes place.  That likely explains the differences that you are getting.  

In practice, this means that you can just leave the covariates as they are in your data (like we do in our application).  And, for (ii), I think that it is fine to use sector and region factors as you did.

Brant

**Comment by DimExa** [comment]
Hi Brant,

Thank you for the quick reply. I reproduced the analysis, replacing the post-treatment values of the covariates of treatment group with the values they have one year before treatment, keeping the rest of the values to be time varying and indeed I obtain identical results as before.

One correction, in my previous post, I wanted to write that "...I see that county population is NOT TIME-VARIANT in your case...", that's why I got confused (below a snapshot of your dataset). 

> mpdta
     year countyreal     lpop     lemp first.treat treat
866  2003       8001 5.896761 8.461469        2007     1
841  2004       8001 5.896761 8.336870        2007     1
842  2005       8001 5.896761 8.340217        2007     1
819  2006       8001 5.896761 8.378161        2007     1
827  2007       8001 5.896761 8.487352        2007     1
937  2003       8019 2.232377 4.997212        2007     1
938  2004       8019 2.232377 5.081404        2007     1
939  2005       8019 2.232377 4.787492        2007     1
940  2006       8019 2.232377 4.990433        2007     1
941  2007       8019 2.232377 5.036953        2007     1
951  2003       8023 1.298282 2.197225        2007     1
952  2004       8023 1.298282 2.302585        2007     1
953  2005       8023 1.298282 2.772589        2007     1
954  2006       8023 1.298282 1.945910        2007     1
955  2007       8023 1.298282 2.995732        2007     1

As far as I understant from your paper, lpop is the county population in 2000 right?

However, in my case, log_l (one of the covariates) does change over time (below a snapshot of my dataset).

> dat
   year sector country firm_id age    log_y    log_l log_labprod_y log_capital_intensity sector_FE      m_share log_m_share
1  2009     61      BE     830  40 18.01919 5.533389      12.48580              12.85172         3 4.673265e-05   -9.971067
2  2010     61      BE     830  41 18.16201 5.488938      12.67307              12.94375         3 2.701907e-05  -10.518968
3  2011     61      BE     830  42 18.21187 5.488938      12.72293              12.97920         3 2.336025e-05  -10.664475
4  2012     61      BE     830  43 18.40692 5.545177      12.86174              12.93179         3 2.929745e-05  -10.438010
5  2013     61      BE     830  44 18.54091 5.613128      12.92778              12.87448         3 3.152195e-05  -10.364826
6  2014     61      BE     830  45 18.67331 5.594711      13.07860              12.94554         3 2.672156e-05  -10.530040
7  2015     61      BE     830  46 18.70877 5.560682      13.14809              13.07643         3 2.373385e-05  -10.648608
8  2016     61      BE     830  47 18.74721 5.513429      13.23378              13.22469         3 2.177719e-05  -10.734647
9  2017     61      BE     830  48 18.77870 5.513429      13.26528              13.29060         3 2.230341e-05  -10.710771
10 2009     61      BE     831  38 16.62933 5.043425      11.58590              12.17860         3 1.162507e-05  -11.362346
11 2010     61      BE     831  39 16.57220 4.919981      11.65222              12.25739         3 5.510927e-06  -12.108778
12 2011     61      BE     831  40 16.58080 4.867534      11.71327              12.12839         3 4.572071e-06  -12.295544
13 2012     61      BE     831  41 16.71354 4.844187      11.86935              12.08482         3 5.387676e-06  -12.131396
14 2013     61      BE     831  42 16.76483 4.804021      11.96081              12.05207         3 5.336706e-06  -12.140902
15 2014     61      BE     831  43 16.79811 4.770685      12.02742              12.13031         3 4.097040e-06  -12.405246
16 2015     61      BE     831  44 16.81409 4.718499      12.09559              12.15017         3 3.568763e-06  -12.543292
17 2016     61      BE     831  45 16.93942 4.691348      12.24807              12.28013         3 3.571823e-06  -12.542435
18 2017     61      BE     831  46 16.98637 4.682131      12.30423              12.31906         3 3.715082e-06  -12.503110

So, the main difference between my dataset and the one of your application is that some of my covariates do change over time and they do not behave like lpop. But as far as I understand from your response, I can still leave them as they are, right?

Thank you again for your time,
Dimitris

**Comment by bcallaway11** [comment]
Hi Dimitris,

Ah, yes, I see how this is confusing.  I need to go back through and correct our documentation --- I get this sort of question a lot, and I realize now that our documentation is both unclear and contradicts itself on this front.

Everything you said though is totally right.  You can leave the covariates in your application as they are, and the way the code actually treats them is how I described in my previous post.

Thanks!
Brant

**Comment by bcallaway11** [comment]
The incorrect documentation discussed here is fixed now, see: https://bcallaway11.github.io/did/articles/did-basics.html

and, in particular, the bullet point starting "The did package allows for incorporating covariates"

**Comment by jtorcasso** [comment]
Would it be possible to include support for time-varying covariates as a new feature? 

Let's say we are evaluating a small program that rolls out in different zips across the US. We expect that the program won't affect things like state population or the unemployment rate, but that these could confound our estimate of the treatment effect. So we'd like to control this time-varying covariates. 

Within the existing package, we could estimate the change in the unemployment rate between two fixed time points and include this as a time invariant control, but if we have staggered roll out, a fixed time point may not line up well depending on each group's treatment timing. We could then include changes from other time points, but this doesn't seem very parsimonious. 

Instead, if the software supported time-varying controls separate from time-invariant controls, each 2x2 DID could calculate the change in the time-varying control (between the reference period and current time period) and then account for this covariate similarly to how the software handles time-invariant controls. 

Would this be possible/useful?

**Comment by bcallaway11** [comment]
@jtorcasso, short answer: yes.  I'm going to open up a new issue related to time varying covariates.
