### ISSUE TITLE
Improving bootstrap performance: mboot

### ISSUE THREAD

**Issue by antrologos** [bcallaway11/did#72]
Hi Brant and Pedro, again... 

I've noticed the performance of `att_gt` is considerably dependent on how fast the bootstrap executes. With large datasets and more repetitions, a calculation which took a few seconds/minutes can escalate to several minutes or even hours. 

I could not completely solve this issue, but here it goes a suggestion that can improve the speed of `mboot` up to 3 times (or more) -- and the speed of `att_gt` and `compute.aggte` up to 10 times (or more). I know you are planning to implement parallel processing. But maybe this simple implementation ca be helpful for some cases. 
This bit of original code can be replaced by the one I wrote, which is further bellow

```
# Original piece of code inside mboot
bout <- lapply(1:biters, FUN = function(b) {
        if (length(clustervars) > 0) {
            n1 <- length(unique(dta[, clustervars]))
            Vb <- matrix(sample(c(-1, 1), n1, replace = T))
            Vb <- cbind.data.frame(unique(dta[, clustervars]),  Vb)
            Ub <- data.frame(dta[, clustervars])
            Ub <- Vb[match(Ub[, 1], Vb[, 1]), ]
            Ub <- Ub[, -1]
        }
        else {
            Ub <- sample(c(-1, 1), n, replace = T)
        }
        Rb <- sqrt(n) * (apply(Ub * (inf.func), 2, mean))
        Rb
    })
```

```
# Piece of code written by me
if(length(clustervars > 0)){
                n1 <- length(unique(dta[, clustervars]))
                Vb <- matrix(sample(c(-1, 1), n1*biters, replace = T), ncol = biters)
                Vb <- cbind.data.frame(unique(dta[, clustervars]), Vb)
                Ub <- data.frame(dta[, clustervars])
                Ub <- Vb[match(Ub[, 1], Vb[, 1]), ]
                Ub <- Ub[, -1]
}else {
                Ub <- matrix(sample(c(-1, 1), n1*biters, replace = T), ncol = biters)
}
        
bout = lapply(1:biters, function(i) {
                sqrt(n) * (apply(Ub[,i] * (inf.func), 2, mean))
        })
```

**Comment by bcallaway11** [comment]
Hi Rogerio,

Thanks for these.  I really haven't tested our code at all with the large size datasets that you are using, so these comments are much appreciated.  Please keep them coming if you run into other issues or ideas for improvements.

Brant

**Comment by bcallaway11** [comment]
Hi Rogerio,

For the new version of the code, we re-wrote the multiplier bootstrap code in C++ and are seeing big improvements in computation time.  See this post: https://bcallaway11.github.io/posts/did-improvements for more details.

Brant
