### ISSUE TITLE
use with unbalanced panels

### ISSUE THREAD

**Issue by jaquesfree** [bcallaway11/did#76]
Thank you for this great package.  I have two questions regarding its use with unbalanced panels and the setting allow_unbalanced_panel=TRUE
Firstly, I noticed that when I use this setting (set allow_unbalanced_panel=TRUE) with a balanced panel I get a different result (ATT) using the outcome regression estimation method and including covariates than when I set allow_unbalanced_panel=FALSE.  This is not the case when I do not include any covariates.  Do you know why this might be the case?  If the panel is balanced, shouldn't the data/results be the same regardless of whether allow_unbalanced_panel is set to TRUE or FALSE. 
Secondly, when using this setting (allow_unbalanced_panel=TRUE) with an unbalanced panel, I am curious as to how it calculates the group time average treatment effects.  Does it subtract the average pre-treatment outcome for all units in the respective group in the pre-treatment period from the average post-treatment outcome for all units in the respective group in the post-treatment period regardless of whether the units in the post-treatment period differ from the units in the pre-treatment period or does it only compare pre and post-treatment outcomes for units present in both the pre and post periods.

**Comment by bcallaway11** [comment]
Thanks for the message, these are good questions.  Let me answer the second question first.  In the case of an unbalanced panel, we do the first thing that you said --- we subtract average pre-treatment outcomes for all units in a particular group from average post-treatment outcomes for all available units in both periods.  There's an embedded assumption here about attrition being at-random, but this would be the case for most panel data approaches that allow for an unbalanced panel.

For the first one, yes, you should get the same estimates if you have a balanced panel.  One possible explanation that comes to my mind: are the covariates time varying?  If they are, then I think our code would give results that are not exactly the same when using the unbalanced_panel=TRUE option.

Brant

**Comment by jaquesfree** [comment]
Thanks very much for these responses.  Yes, they are time varying so that would explain the difference.  Based on your responses in earlier threads, I thought it was ok to use time varying covariates and let the package set the value of the covariates to be equal to their value in the pre-treatment period.  If this is correct, which results do you think would be more accurate/consistent with your method (those that I obtained using the unbalanced_panel=TRUE option or those that I obtained using the allow_unbalanced_panel=FALSE option)?

**Comment by bcallaway11** [comment]
My sense is that things actually become quite a bit trickier (both conceptually and in terms of coding) with an unbalanced panel and time varying covariates.  In principle, it seems like we could try to figure out the pre-treatment value of the covariates, but it is also challenging because not all units are available in all years.  

Is your panel "very" unbalanced?  If you have important, time varying covariates then I'd tentatively recommend just balancing the panel if the panel is not too unbalanced.  On the other hand, if the panel has lot of missing data, then it probably makes sense to follow the unbalanced panel route.

I'm also just curious --- are your results very sensitive to the choice between the balanced and unbalanced panel options?

**Comment by jaquesfree** [comment]
Thanks.  This provides very helpful guidance.  Yes, my panel is very unbalanced with lots of missing data and, regarding the sensitivity to the balanced and unbalanced panel options (when using a balanced panel with time varying covariates and the outcome regression estimation method), I am seeing that the results are significantly different and lead to a sign change in one of the values of the aggregated ATT/attge measures (though the choice of option does not affect the statistical significance of the results).

**Comment by bcallaway11** [comment]
This is interesting.  If you don't include any covariates at all, do you still get big differences between estimates that use the balanced panel relative to the full unbalanced panel?

What I am wondering is if the difference is driven by the composition of the sample changing with balanced or unbalanced panel, or if it is actually because of the time varying covariates.

**Comment by jaquesfree** [comment]
The specific difference that I noted in my original post was after I balanced my panel so I don't think it could have been due to a change in the composition of the sample.  Specifically, I balanced my panel and ran the package twice (once with allow_unbalanced_panel set to TRUE and once with allow_unablanced_panel set to FALSE) using time varying covariates and the outcome regression estimation method and expected to get the same results since the panel was already balanced-but saw a difference.  When I tried again without covariates, both options produced the same results (there was no longer a difference).  Using the full unbalanced panel, I got very different results as well both when I included and did not include covariates but this did not surprise me due to the change in the composition of the sample that you mention, which would have been significant due to a lot of missing data.

**Comment by pedrohcgs** [comment]
If you are getting different results with doubly robust estimator, the
reason may be that with an unbalanced panel we ended up modeling the
conditional outcome evolution of the treated units, but  with balanced
panel that is not required.

Do you get the same point estimates if you set est_method = "reg" ?


==============================
*Pedro H. C. Sant'Anna*
Department of Economics
Vanderbilt University
615-875-8448 (phone)
***@***.***
<https://email.vanderbilt.edu/owa/redir.aspx?SURL=R33SAibMcqASxYI7tVlx3_2Xx09NkN6m1ZKVuyK8lL42lUjfQp_SCG0AYQBpAGwAdABvADoAcABlAGQAcgBvAC4AaAAuAHMAYQBuAHQAYQBuAG4AYQBAAHYAYQBuAGQAZQByAGIAaQBsAHQALgBlAGQAdQA.&URL=mailto%3apedro.h.santanna%40vanderbilt.edu>
https://pedrohcgs.github.io
===============================

**Comment by jaquesfree** [comment]
I do not.  The point estimates are different if I include the covariates and set est_method="reg."  They are the same if I do not include the covariates.

**Comment by bcallaway11** [comment]
I'm closing this particular issue.  I opened a related (more general) issue about unbalanced panels here: #90
