### ISSUE TITLE
Comparison period when g>t, i.e., when looking at pre-treatment effects, is t-1, rather than g-1

### ISSUE THREAD

**Issue by jtorcasso** [bcallaway11/did#86]
Suppose no anticipation, and we consider estimating ATT(g,t). Then when g <= t, the comparison period is g-1. But when g > t, the package will use t-1 as the comparison period. Is there a reason why g-1 is not used as the comparison period when g > t? To my knowledge, the paper only refers to g-1 as a comparison period, regardless of the value of t. 

Using t-1 as the comparison period also leads to pre-trends that look closer to zero, since you compare adjacent periods, rather than with a common comparison period (e.g., g-1).

Just wondering if this is a bug, or if there is a particular reason for this choice.

Thanks for a very useful package, Jake

**Comment by jtorcasso** [comment]
I see that you've already discussed this 

https://github.com/bcallaway11/did/issues/27

**Comment by bcallaway11** [comment]
Hi Jake,

Yes, a longer discussion is available in this [post](https://bcallaway11.github.io/posts/event-study-universal-v-varying-base-period).

We'll have the option to use a "universal"/fixed base period in the new version of the code which should be available in the next week or two.

Brant
