### ISSUE TITLE
Error in aggte

### ISSUE THREAD

**Issue by adebiasi21** [bcallaway11/did#87]
I am attempting to run aggte with type = "dynamic." I first run att_gt, clustering standard errors by neighborhood and including one control: 

`history0_attgt <- att_gt(yname = "crime",
                         tname = "new_qrtr",
                         idname = "parcelid",
                         gname = "new_group",
                         xformla = ~tpc,
                         clustervars = "neighbor10",
                         data = mydata0,
                         print_details=TRUE,
                         est_method = "dr")
`
I get 50 warnings related to there not being enough control units for group 2. 

```
1: In compute.att_gt(dp) :
  Not enough control units for group 2 in time period 2 to run specified regression
2: In compute.att_gt(dp) :
  Not enough control units for group 2 in time period 3 to run specified regression
3: In compute.att_gt(dp) :
  Not enough control units for group 2 in time period 4 to run specified regression
4: In compute.att_gt(dp) :
  Not enough control units for group 2 in time period 5 to run specified regression
5: In compute.att_gt(dp) :
  Not enough control units for group 2 in time period 6 to run specified regression
6: In compute.att_gt(dp) :
  Not enough control units for group 2 in time period 7 to run specified regression
```
..... 

```
47: In compute.att_gt(dp) :
  Not enough control units for group 18 in time period 2 to run specified regression
48: In compute.att_gt(dp) :
  Not enough control units for group 19 in time period 2 to run specified regression
49: In compute.att_gt(dp) :
  Not enough control units for group 20 in time period 2 to run specified regression
50: In compute.att_gt(dp) :
  Not enough control units for group 21 in time period 2 to run specified regression

```
I then run the aggte command, making sure to include na.rm = TRUE:

`history0_dynamic <- aggte(history0_attgt, type = "dynamic", na.rm=TRUE)`

When I go to plot the outcome, I get the following error:

`> plot(history0_dynamic)
Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' is a list, but does not have components 'x' and 'y'`

Like before, there are 50 warnings associated, all having to do with the following:

` In weights.ind * 1 * (G == group[k]) :
  longer object length is not a multiple of shorter object length`

I understand that I do not have enough control units in group 2. However, I thought that by setting na.rm = TRUE for aggte that this would allow me to view a dynamic 'event study' plot. Is there a work-around here? I appreciate all the help that can be provided.

**Comment by bcallaway11** [comment]
Let me check this out today.  We have been have a little bit of trouble with that part of the code.  I'll keep you posted (hopefully today, but may be tomorrow).

Brant

**Comment by bcallaway11** [comment]
I tentatively think that this should be fixed now.  Please try running

```
devtools::install_github("bcallaway11/did")
```
to get the updated version of the code.  I think that should also prompt you to update the `BMisc` package, which you should do.  If not, please also run

```
devtools::install_github("bcallaway11/BMisc")
```

I think this will fix the issue you are running into with respect to the event study (but please let me know if it does not!).

**Comment by adebiasi21** [comment]
Thanks so much, Brant! I will give this a try. Would you mind keeping this issue open for a day or two longer? I'm working with a very large dataset; the program takes a while to run. As always, I appreciate your help!

**Comment by adebiasi21** [comment]
Thank you for keeping this issue open. Unfortunately, the `Error in xy.coords(x, y, xlabel, ylabel, log) : 'x' is a list, but does not have components 'x' and 'y'` persists after `devtools::install_github("bcallaway11/BMisc")`

**Comment by bcallaway11** [comment]
Uh oh, I thought that would fix it.

Would it be possible to email me a (very small) subset of your data or some way to replicate the error that you're getting?  My email is brantly.callaway@uga.edu
