### ISSUE TITLE
Time Invariant Controls 

### ISSUE THREAD

**Issue by apodges** [bcallaway11/did#91]
How does the DID approach treat time invariant variables? In the TWFE framework, which I am most used to, my understanding is that the there is no need to include time invariant variables as controls; they are handled by the inclusion of time fixed effects.  How should one think about time invariant variables in the DID framework? Does the approach control for them, like in the case of TWFE approach? Or, am I thinking about this wrong?

**Comment by pedrohcgs** [comment]
The role of covariates in DiD allowing for covariate-specific trends. In
TWFE, if you really wanted to do this, you would interact time-invariant
covariates with cohort dummies and with time dummies.

We implicitly do all that by allowing all slope coefficients in outcome
regressions to vary with time. We also include the time-invariant
covariates into the "generalized" propensity score. Here, again, the "logit
betas" are allowed to change with cohort.

Hope this helps.

Thanks,
===============================
*Pedro H. C. Sant'Anna*
Department of Economics
Vanderbilt University
615-875-8448 (phone)
***@***.***
<https://email.vanderbilt.edu/owa/redir.aspx?SURL=R33SAibMcqASxYI7tVlx3_2Xx09NkN6m1ZKVuyK8lL42lUjfQp_SCG0AYQBpAGwAdABvADoAcABlAGQAcgBvAC4AaAAuAHMAYQBuAHQAYQBuAG4AYQBAAHYAYQBuAGQAZQByAGIAaQBsAHQALgBlAGQAdQA.&URL=mailto%3apedro.h.santanna%40vanderbilt.edu>
https://pedrohcgs.github.io
===============================

**Comment by frederickluser** [comment]
Dear Pedro, Dear Brant,

I don't understand this and would like to quickly follow up on this. Let's assume I would estimate a TWFE with region-time fixed effects - so the time-constant period-effects were allowed to vary across regions. How would I do that with your estimator? Is this already happening anyway, could I include region as a covariate in _xformla_ or is not possible? Thanks a lot!

**Comment by bcallaway11** [comment]
Hi Frederic,

Yes, you are right.  You would just include it as a control in xformla.
Hope this helps, and I'm happy to follow up if needed.

Brant
