### ISSUE TITLE
[bug] unused argument (balance_panel = FALSE) while running att_gt function

### ISSUE THREAD

**Issue by filipemsc** [bcallaway11/did#92]
I just installed the new version of the `did` package (2.1) and obtained the following error while trying to run a simple code with it: 

```{r}
library(did)
#> Warning: package 'did' was built under R version 4.1.2
data(mpdta)

out1 <- att_gt(yname="lemp",
               tname="year",
               idname="countyreal",
               gname="first.treat",
               xformla=NULL,
               data=mpdta)
#> Error in BMisc::panel2cs2(disdat, yname, idname, tname, balance_panel = FALSE): unused argument (balance_panel = FALSE)
```

**Comment by pedrohcgs** [comment]
Could you also update the BMisc package? That should do it.

Thanks
===============================
*Pedro H. C. Sant'Anna*
Department of Economics
Vanderbilt University
615-875-8448 (phone)
***@***.***
<https://email.vanderbilt.edu/owa/redir.aspx?SURL=R33SAibMcqASxYI7tVlx3_2Xx09NkN6m1ZKVuyK8lL42lUjfQp_SCG0AYQBpAGwAdABvADoAcABlAGQAcgBvAC4AaAAuAHMAYQBuAHQAYQBuAG4AYQBAAHYAYQBuAGQAZQByAGIAaQBsAHQALgBlAGQAdQA.&URL=mailto%3apedro.h.santanna%40vanderbilt.edu>
https://pedrohcgs.github.io
===============================

**Comment by filipemsc** [comment]
Worked! Thanks
