### ISSUE TITLE
Honest DiD

### ISSUE THREAD

**Issue by frederickluser** [bcallaway11/did#99]
Dear Brant and Pedro

It's not an issue but really just a question. I saw your great presentations at the YoungStatS webinar and Pedro demonstrated in the discussion the wrapper for the Honest DID package. I installed the newest version from github for both packages, but I don't see the `honest_did `function. Is it not available yet?

Thanks a lot and Best, Frederic

**Comment by bcallaway11** [comment]
Hi Frederic,

It's not quite finalized, but I do have code that I could send you.  If you send me an email (brantly.callaway@uga.edu), I'll send the code along to you, and I'm almost sure it will work for you.  We'll post something publicly once we have fully tested it/resolved some implementation issues.

Brant
